name: portfolio
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  sensors_plus: ^1.3.2
  
  sqflite:
  firebase_core: ^1.20.0
  firebase_database: ^9.0.20
    
  cupertino_icons: ^1.0.2
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:
  assets: 
      - assets/images/
  fonts:
    - family: Nuitro
      fonts: 
        - asset: assets/fonts/Nunito-VariableFont_wght.ttf

    
  
  uses-material-design: true

 