name: portfolio
description: "The portfolio app for the prtfolio project. It is a Flutter application that showcases the portfolio of a developer. The app includes features such as authentication, cloud storage, and local database management."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Router
  octopus: ^0.0.9

  # State Management
  flutter_bloc: ^9.1.1
  provider: ^6.1.4

  equatable: ^2.0.7
  
  # Shared Preferences
  shared_preferences: ^2.5.3
  
  # Async 
  rxdart: ^0.28.0
  async: 2.12.0

  # Authentication
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  formz: ^0.8.0

  # Notifications
  flutter_local_notifications: ^19.1.0
  android_alarm_manager_plus: ^4.0.7
  timezone: ^0.10.1

  # Images
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  cached_network_image: ^3.4.1
  
  # Path provider
  path: ^1.9.1

  # Permissions
  permission_handler: ^12.0.0+1

  # Ios app tracking
  app_tracking_transparency: ^2.0.6+1

  # Url strategy
  url_strategy: ^0.3.0

  # Local database 
  drift: ^2.26.0
  sqlite3_flutter_libs: ^0.5.32
  
  # Url launcher
  url_launcher: ^6.3.1

  # Uuid generator
  ulid: ^2.0.1

  # Logger
  logging: ^1.3.0

  # Freezed 
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # Linter
  sizzle_lints: ^2.1.7
  flutter_localizations:
    sdk: flutter
  intl: any
  meta: ^1.16.0
  path_provider: ^2.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter

  drift_dev: ^2.26.0
  freezed: ^3.0.6
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  flutter_native_splash: ^2.4.6
 
  flutter_lints: ^5.0.0

flutter:
  generate: true

  uses-material-design: true
